sudo: true

dist: xenial

language: python

python:
  - 3.7

before_install:
  - pip install codecov coverage

install:
  - pip install pyserial

script:
  - python -m unittest discover
  - nosetests -v --with-coverage

after_success:
  - codecov
