sudo: true

dist: xenial

language: python

python:
  - 3.7

before_install:
  - pip install codecov

install:
  - pip install pyserial

script:
  - python -m unittest discover tests/*
  - coverage run tests/*/*.py

after_success:
  - codecov
