sudo: true

dist: xenial

language: python

python:
  - 3.7

before_install:
  - pip install codecov pytest-cov

install:
  - pip install -r requirements.txt

script:
  - pytest
  - pytest --cov=./

after_success:
  - codecov
