sudo: true

dist: xenial

language: python

python:
  - 3.7

before_install:
  - pip install codecov pytest-cov pipenv

install:
  - pipenv install --system

script:
  - pytest --cov=./

after_success:
  - codecov
