sudo: true

dist: xenial

language: python

python:
  - 3.7

before_install:
  - pip install codecov

install:
  - pip install pyserial

script:
  - python -m unittest discover tests/*
  - nosetests -v --with-coverage --cover-package=maodevice

after_success:
  - codecov
